apiVersion: v1
kind: Service
metadata:
  name: legacy
  namespace: amrayn
spec:
  selector:
    app: legacy
  type: ClusterIP
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy
  namespace: amrayn
spec:
  selector:
    matchLabels:
      app: legacy
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: legacy
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - image: ghcr.io/amrayn/legacy:1.16.75
        name: legacy
        ports:
        - containerPort: 80
          name: legacy
        envFrom:
          - configMapRef:
              name: env
