version: '3.9'

services:

  legacy:
    image: ghcr.io/amrayn/legacy:dev
    container_name: amr_legacy
    build:
      context: ../
      args:
        - registry=ghcr.io
        - scope=amrayn
    depends_on:
      - db
    ports:
      - 8083:80
    env_file:
      - ../base/dev.env
    volumes:
      - ../:/var/www/html/
